add iteration over error models

diff --git a/run_simu_chain b/run_simu_chain
--- a/run_simu_chain
+++ b/run_simu_chain
@@ -2,12 +2,14 @@
 
 # defaults
 version=""
-n_repetitions="5"
+n_repetitions="10"
 models="exp1_con_rho0.05 exp1_con_rho0.10 exp1_con_rho0.15"
 
 input_version="version_TEST"
 
 binnings="sb1,sb2,sb3"
+
+errors="stat syst norm full"
 
 # parse command line
 function PrintUsage()
@@ -19,11 +21,17 @@ function PrintUsage()
 	echo "    -models <string>         space-separated list of models"
 	echo "    -input-version <string>  version of the input"
 	echo "    -binnings <string>       comma-separated list of binnings"
+	echo "    -errors <string>         space-separated list of error models"
+	echo "    -fast                    use settings for a fast check"
 }
 
 while [ -n "$1" ]
 do
 	case $1 in
+		"-h" | "-help" | "--help")
+			PrintUsage
+			exit 0
+			;;
 		"-version")
 			shift
 			version="$1"
@@ -43,6 +51,15 @@ do
 		"-binnings")
 			shift
 			binnings="$1"
+			;;
+		"-errors")
+			shift
+			errors="$1"
+			;;
+		"-fast")
+			n_repetitions="5"
+			models="exp1_con_rho0.10"
+			binnings="sb1"
 			;;
 		*)
 			echo "ERROR: parameter '$1' not understood."
@@ -79,26 +96,53 @@ do
 	mkdir -p "$model"
 	cd "$model"
 
-	for seed in `seq 1 $n_repetitions`
+	for error_model in $errors
 	do
-		echo "  - $seed"
+		echo "  - $error_model"
 
-		mkdir -p "seed_$seed"
-		cd "seed_$seed"
+		mkdir -p "errors_$error_model"
+		cd "errors_$error_model"
 
-		$BASE_DIR/.simu_make_histograms -model-file "../../models.root" -model-obj "$model/g_dsdt_CH" \
-			-input-file "$BASE_DIR/data/input/$input_version/import.root" -binnings "$binnings" -seed $seed \
-			-sim-stat-err 1 -sim-syst-err 1 -sim-norm-err 1\
-			&> "histograms.log" || exit 22
+		e_stat="0"
+		e_syst="0"
+		e_norm="0"
 
-		$BASE_DIR/.make_fit &> "fit.log" || exit 23
+		if [ "$error_model" == "stat" ]; then e_stat="1"; fi
+		if [ "$error_model" == "syst" ]; then e_syst="1"; fi
+		if [ "$error_model" == "norm" ]; then e_norm="1"; fi
+
+		run_fits="0"
+		if [ "$error_model" == "full" ]; then run_fits="1"; fi
+
+		for seed in `seq 1 $n_repetitions`
+		do
+			echo "    -> $seed"
+
+			mkdir -p "seed_$seed"
+			cd "seed_$seed"
+
+			$BASE_DIR/.simu_make_histograms -model-file "../../../models.root" -model-obj "$model/g_dsdt_CH" \
+				-input-file "$BASE_DIR/data/input/$input_version/import.root" -binnings "$binnings" -seed $seed \
+				-sim-stat-err $e_stat -sim-syst-err $e_syst -sim-norm-err $e_norm\
+				&> "histograms.log" || exit 22
+
+			if [ "$run_fits" == "1" ]
+			then
+				$BASE_DIR/.make_fit &> "fit.log" || exit 23
+			fi
+		
+			cd ..
+		done
+
+		$BASE_DIR/.simu_process_histograms -seed-min 1 -seed-max $n_repetitions -binnings "$binnings" &> "process_histograms.log" || exit 24
+
+		if [ "$run_fits" == "1" ]
+		then
+			$BASE_DIR/.simu_process_fits -seed-min 1 -seed-max $n_repetitions &> "process_fits.log" || exit 25
+		fi
 
 		cd ..
 	done
-
-	$BASE_DIR/.simu_process_histograms -seed-min 1 -seed-max $n_repetitions -binnings "$binnings" &> "process_histograms.log" || exit 24
-
-	$BASE_DIR/.simu_process_fits -seed-min 1 -seed-max $n_repetitions &> "process_fits.log" || exit 25
 
 	cd ..
 done
